### PR TITLE
feat/crop add cropping method

### PR DESCRIPTION
**Pull request by wingleungchoi**
@boazsegev  
- to add crop method in page methods
- [X0, Y0, X_max, Y_max], where (X0, YO) is the starting co-ordinate(left low corner) of cropping section and (X_max, Y_max) is the ending porint co-ordinate (right upper corner)
- also change the page size, MediaBox and CropBox

### CODE REVIEW

**Comment by boazsegev** [comment]
Hello Wing Leung,

First let me thank you for your pull request.

I love the idea of adding a `crop` helper method. 

I also like that an empty `crop` will actually return `page_size`, this makes sense... although, it might make more sense to return the cropbox (or `nil`), so `crop` could be used to check if a crop was already applied and update the cropbox (or create a new one)... I'm not sure which one is better.

However, I feel the code could probably be optimized and streamlined.

Is it okay if we tried optimizing the code together before we we merged the pull request?

My thoughts are that we should clear up any temporary variables, make the code a little more DRY and perhaps recycle existing objects (such as the cropbox/mediabox arrays) instead of creating new ones.

Remember that Ruby is a scripting language, so there's no "compile time" optimizations. Every variable we use, even temporary ones, use up memory and wait for the garbage collection... so using `c_mediabox` and `c_cropbox` seems wasteful.

Also, I was wondering why we need this:

```ruby
insert_content "q\n1 0 0 1 #{-x_move} #{-y_move} cm\n", 0
```

Do we neet to move the contents? This could be less expected then changing the crop values. Also, can't we get the same effect by setting the offset of the crop?

I mean, crop could be used to change the crop rather then create a new crop.

I would love to read your opinion about this before we merge the pull request.

I guess my questions to you are:

1. Do you think `page.crop(nil)` should return `page.page_size` or `page.cropbox`? Why?

2. Do you think the user expects the crop-box to move the XY?

3. Should `crop` update `mediabox` as well as `cropbox`? Maybe updating `cropbox` is enough?

At the moment, if I was cropping a page, I would probably do this:

```ruby
# crop to the size of 10.0, 10.0, 612.0, 792.0
page.fix_rotation # make sure I'm working on what I saw.
# set the X0 and Y0 offset
page.page_size[0] += 10.0
page.page_size[1] += 10.0
# set page_size (either mediabox or cropbox) to the smaller of the two values.
# I'm using the offset from the new X0 and Y0 to set the Xmax and Ymax
page.page_size[2] = page.page_size[0] + 612.0 - 10.0 if ((page.page_size[0] + 612.0 - 10.0) < page.page_size[2])
page.page_size[3] = page.page_size[1] + 792.0 - 10.0 if ((page.page_size[1] + 792.0  - 10.0) < page.page_size[3])
```

This seems shorter and I think the results are more what I would expect. Also, this way I don't need to update the content stream and I know I'm not cropping in a way that makes the page larger then it is (I'm not cropping "up")...

How would you crop a page without using the `crop` method?

**Comment by wingleungchoi** [comment]
@boazsegev 
Thank you for pointing out my mistakes and i did not know the variables will slow down performance. I followed  your suggestion to the method#crop speed up a lots :+1: 
I currently in my app (Rails project) reopen CombinePDF::Page_Methods in initizers.

Q1.Do you think page.crop(nil) should return page.page_size or page.cropbox? Why?
It is my mistake. I think It should return self for chaining.
Q2.Do you think the user expects the crop-box to move the XY?
It is my mistake too. :see_no_evil: 
Q3.Should crop update mediabox as well as cropbox? Maybe updating cropbox is enough?
Maybe crop should update mediabox and cropbox.
http://www.prepressure.com/pdf/basics/page-boxes, according to this article, maybe method#page_size should return mediabox first than cropbox.  `mediabox || cropbox`

**Comment by boazsegev** [comment]
Hello Wing Leung,

Thank you for your quick reply.

It's important for me that you understand - I don't think your code had mistakes. It was a good first draft... but we rewrite a few times until we find a better version. This is a normal part of the process.

To answer your questions:

Q1. `page.crop(nil)`? 

Thinking more deeply, I wonder - what would the average user expect `crop(nil)` to do?

I'm guessing `crop(nil)` is like "no-crop", of `page.crop(page.mediabox)` (with offset adjustments)...

So maybe  `crop(nil)` should clear the `cropbox` and return `self`...

What do you think?

Q2. Moving the XY?

I think that the XY shouldn't move. Cropping isn't the same as a resize. Resizing will move the XY

I think the code I wrote ignores this difference and that this is a mistake... `crop` should probably only affect the `cropbox`, without changing anything else. This seems to be the most obvious behavior.

Q3. Updating MediaBox?

After reading the article you sent, I believe that the `crop` method should only effect the `CropBox` and NOT the `MediaBox`.

Q4. `page_size`

I think `page_size` should return the size of the visible page (what is printed or displayed on screen). I think that most users aren't very aware of the distinction between `MediaBox` and `CropBox`, so using `page_size` is an easy way to get the information they need without getting into a lot of details.

The people who want a specific value can use the `mediabox` and `cropbox` methods.

Maybe the `crop` function should look like this?

```ruby
def crop box=nil
# no crop box? clear any cropping.
if !box
   cropbox = nil
   return self
end
fix_rotation # Should we do this?

# crop to the size of box[0], box[1], box[2], box[3]

# set the new cropbox
self[:CropBox] = [
   page_size[0] + box[0], # update X0
   page_size[1] + box[1], # update Y0
   (  (page_size[2]  > page_size[0] + box[2]) ?
            (page_size[0] + box[2]) :
            page_size[2]     ), # choose the smaller value
   (  (page_size[3]  > page_size[1] + box[3]) ?
            (page_size[1] + box[3]) :
            page_size[3]     ) # choose the smaller value
]

# return self for chaining
self
end
```

What do you think?

Should we enforce `fix_rotation`? Maybe someone made computations in relation to the existing page-size and this changes the whole thing?

**Comment by wingleungchoi** [comment]
Q1. page.crop(nil)?

I think an average user expect crop(nil) to "no-crop" and also it is consistent method#resize. parameter nil means `no resize`

Q2. Moving the XY?

I agreed that the XY shouldn't move.

Q3. Updating MediaBox?

From the article i sent, `The GWG industry association recommends not to use the CropBox at all`. I think we should also change mediabox becuase users will expect the actual page size changes after crop method. 
Q4. page_size
I think it is quite personal preference. I have no opinions on this point.
However, i agreed that `The people who want a specific value can use the mediabox and cropbox methods.`

Q5.  fix_rotation
I think It might not be necessary on crop method.

**Comment by boazsegev** [comment]
Hi, Sorry for the long delay... I wanted to sleep on this and give it some thought, but then a few projects came in and I got super busy with my music (I play piano and I'm a songwriter).

I read through the link you sent me and a few articles about the GWG association (The Ghent Workgroup).

It seems to me that the GWG's recommendations are aimed at the specific needs of the print and publishing industry. I am more worried about data loss and supporting developers that need functionality.

So far, I have kept the information intact, so that most operations could be reversible.

For example, the `resize` function resizes both the mediabox and the cropbox preserving each element's unique data. i.e., if the MediaBox was [0,0,100,100] and the CropBox [10, 10, 90, 90], a resize to [0,0,10,10] should produce MediaBox with [0,0,10,10] and a CropBox with [1,1,9,9]... avoiding any data loss, as much as possible.

However, you are right, the CropBox isn't very important. The only difference between using the MediaBox and the CropBox seems to be the ability to "undo" the cropping, which I think of as a positive thing.

If we only change the CropBox, we can undo any crop using `page.cropbox = nil` or `page.crop nil`. But if we change the MediaBox, you can't know what the original page size might have been and there is no way to "undo" the cropping.

On the other hand, people don't expect their PDF's cropping to be removed...

... So I'm really not sure.

I'm also thinking that the `resize(nil)` option was a mistake I made in the API's design... but you are right -  in this case it is more important to stay consistent.

**In summery:**

Q1. page.crop(nil)?

You're right, we should probably return any existing data.

I think it would be best to return `page_size`, as you suggested.

We can have a `page.crop(:clear)` option for clearing the CropBox, if we're cropping the page using the CropBox.

Q2. Moving the XY?

Cool, we agree on this.

Q3. Updating MediaBox?

I'm really not sure what we should do, but I understand your arguments, and if you think we should update the MediaBox, I will trust you.

But, if we update the MediaBox, then it is better to set the CropBox to `nil`. If the CropBox isn't relevant, there is no point in wasting memory and disk space on it.
 
Q5. fix_rotation

Yes I agree we should skip this.

So the end of our discussion looks something like this?

```ruby
def crop box=nil
   # no crop box? clear any cropping.
   return page_size if !box

   # set the MediaBox to the existing page size
   self[:MediaBox] = page_size
   # clear the CropBox
   self[:CropBox] = nil
    # update X0
   self[:MediaBox][0] += box[0]
    # update Y0
   self[:MediaBox][1] += box[1]
    # update X max IF the value is smaller then the existing value
   self[:MediaBox][2] = self[:MediaBox][0] + box[2] if ((self[:MediaBox][0] + box[2])  < self[:MediaBox][2])
    # update Y max IF the value is smaller then the existing value
   self[:MediaBox][3] = self[:MediaBox][1] + box[3] if ((self[:MediaBox][1] + box[3])  < self[:MediaBox][3])
   # return self for chaining
   self
end
```

**Comment by wingleungchoi** [comment]
No worries. Busy always is better than idle.
You are a songwriter. That is cool!

Those concerns you rise. 
Undo-feature in #crop senses great and definitely will be useful in some cases.
Maybe in the future, we can think about refactor method#resize for the case when input is nil.

The method#crop have to be refactored as discussed. Let's see the response form the gem users.

**Comment by boazsegev** [comment]
Hi @wingleungchoi ,

I merged the pull request and made some updates to the function to fix a mistake I made in the math and to add a little bit of type safety...

My tests showed that I had a mistake in the math, when cropping [10,10,90,90], the width should be 80, not 90 like I originally computed.

Please look it over as well (I'll be happy if you test it too, just to make sure it works as expected) and I will release an updated gem version when you tell me it's cool.

:-)

**Comment by wingleungchoi** [comment]
I mistakenly revert the wrong one in previous commits.
The correct width should be `new_size[2] - new_size[0]` Not `new_size[2]` in line 461
The correct height should be `new_size[3] - new_size[1]` Not `new_size[2]` in line 463
Correct one
```
# update X max IF the value is smaller then the existing value
self.page_size[2] = self.page_size[0] + new_size[2] - new_size[0] if ((self.page_size[0] + new_size[2] - new_size[0]) < self.page_size[2])
# update Y max IF the value is smaller then the existing value
self.page_size[3] = self.page_size[1] + new_size[3] - new_size[1] if ((self.page_size[1] + new_size[3] - new_size[1]) < self.page_size[3])
```

Wrong
```
# update X max IF the value is smaller then the existing value
self[:MediaBox][2] = self[:MediaBox][0] + box[2] if ((self[:MediaBox][0] + box[2])  < self[:MediaBox][2])
# update Y max IF the value is smaller then the existing value
self[:MediaBox][3] = self[:MediaBox][1] + box[3] if ((self[:MediaBox][1] + box[3])  < self[:MediaBox][3])
```

**Comment by boazsegev** [comment]
Hi @wingleungchoi ,

Okay, I updated the math, I hope it's okay now. I also added a comment to the documentation, explaining the difference between using the `crop` function for computing the new page size using a relative crop box and setting an absolute page size using the `mediabox=` method.

**Comment by wingleungchoi** [comment]
@boazsegev  those change looks very good. :+1:

**Pull request merged**
