### PR TITLE
Partial support for PDF 1.5 encryption

### PR DESCRIPTION
**Pull request by gyuchang**
1. fix encoding warning for `key`
1. fix typo
1. add support for PDF 1.5 encryption trivial case where
   1. Same filter is specified for streams and strings
   1. RC4 algorithm is specified (CFM == V2)

### CODE REVIEW

**Comment by boazsegev** [comment]
Wow, this looks great! 👍🏻👏🏻👏🏻👏🏻

Can you send me a PDF to test this with?

Thank you very much for taking the time 🙏🏻

**Comment by gyuchang** [comment]
At the moment, I don't have a way to generate an example PDF to reproduce this problem.

The PDF file that breaks the current release was generated by an insurance company for one of our customers and contains personal information. So I am not able to share the actual file.

I will keep researching how to generate same type of PDF.

**Comment by boazsegev** [comment]
Thanks for letting me know.

I totally understand your concern, it's why the PDF files in the automated testing suite aren't published in the repo 👍🏻

If you find something we can test this with, please let me know! 🙏🏻

I'll merge this in and test that current behavior remains... but before I release this in the next version I will need to find a way to validate this patch and add it to the automated testing suite (so future updates don't break it).

Thanks again 👏🏻👏🏻👏🏻

🎉

**Comment by gyuchang** [comment]
I now have more information and patch for AESV2 support. I will open a new PR.

**Comment by yob** [comment]
@boazsegev There's a set of encrypted PDFs generated by Adobe Acrobat 10 in the pdf-reader test suite, and you're welcome to use the in your suite. They're the files called `encrypted_*` in https://github.com/yob/pdf-reader/tree/master/spec/data

**Comment by boazsegev** [comment]
@yob  - Thanks James!

**Pull request merged**
